version: '3'

services:
  web:
    image: nginx:latest
    hostname: server
    volumes:
      - ./:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    hostname: php
    build:
      context: ./docker/php
    volumes:
      - ./:/code
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - database

  database:
    image: mariadb
    hostname: database
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: 12345678
      MARIADB_ROOT_PASSWORD: 12345678
      MARIADB_DATABASE: app
    volumes:
      - ./docker/data/database:/var/lib/mysql
